/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Y2JHBK (https://sketchfab.com/Y2JHBK)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/bullet-9-mm-4cc75b7ef1bc474392c319a47fd97348
Title: Bullet 9 mm
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Models/bullet.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Bullet_bullet_0.geometry}
        material={materials.bullet}
      />
    </group>
  )
}

useGLTF.preload('/bullet.glb')

export default React.memo(Model)

