/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: hoschu (https://sketchfab.com/hoschu)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/walther-ppk-6e2362c3e9894659abf5fa8bcfd7057b
Title: Walther PPK
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


const Gun = React.memo(function Gun(props) {
  const { nodes, materials } = useGLTF('/Models/gun.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes['Mesh_(2)_Default_0'].geometry}
        material={materials.Default}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Fingerprotector_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Trigger_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Secure_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Hammer_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Top_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Rubbers_Default_0.geometry}
        material={materials.Default}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Magazine_Default_0.geometry}
        material={materials.Default}
      />
    </group>
  )
})

export default Gun

useGLTF.preload('/gun.glb')



